### ISSUE TITLE
Wont show in Integration

### ISSUE THREAD

**Issue by DravenSA** [wernerhp/ha.integration.load_shedding#15]
Downloaded from Hacs - No problem
Restarted Home Assistant - No Problems
Go to Settings > Devices & Services > + Add Integration - PROBLEM it is not in the list

Here endith my Problem

**Comment by wernerhp** [comment]
Please check Settings > System > Logs for errors.  You can search for "load_shedding".

**Comment by wernerhp** [comment]
What version of HA are you on?

**Comment by tiaanv** [comment]
FWIW.  I have not problem installing via HACS, and adding the Integration via Front-end.
