### ISSUE TITLE
COCT Schedule not correct

### ISSUE THREAD

**Issue by tiaanv** [wernerhp/ha.integration.load_shedding#16]
Adding Integration with following parameters:
* Search -> "Durbanville" (no effect, but not unexpected)
* Select Area 6 from dropdown

Integration added successfully.

The load-shedding schedule is missing the next loadshedding slot as per my own integration, as well as Loadshedding app (Loadshedding Notifier)

Expected 22:00 12/07/2022
![image](https://user-images.githubusercontent.com/4703398/178542212-8f90c626-3f39-4229-a165-02a6215bcad9.png)

integration: 00:00 13/07/2022
![image](https://user-images.githubusercontent.com/4703398/178542166-3a137091-574c-48f2-8a4b-bf753bf0c568.png)

I have not looked into it myself, but there seems to be a problem.  I will post more replies if I find any clues.

**Comment by wernerhp** [comment]
Should be fixed in v0.4.1.
For interest sake... when the last slot for the day ended on the next day, e.g. 22:00 - 00:30, the day was not incremented. resulting in a slot of 2022-07-12 22:00 - 2022-07-12 00:30 and as a result is filtered out.
