### ISSUE TITLE
Integration doesn't seem to work outside of South Africa

### ISSUE THREAD

**Issue by johannbrink** [wernerhp/ha.integration.load_shedding#17]
Hi all. Do you know if the API you get your data from is blocked outside South Africa? I live in Australia and use Home Assistant. Wanted to use the integration to track when our family members in SA have load shedding, but I get the following message: "Unable to reach Provider. See Logs for details.". Not a big deal but I thought I'd just mention it.

**Comment by wernerhp** [comment]
Never imagined someone outside South Africa would use it! 😁 
Can you reach https://loadshedding.eskom.co.za/ ?
Please post your logs. 
Are you on the latest version of Home Assistant?  I noticed I referenced a new `FlowResultType` that's only available in 2022.7.0 and didn't realize, so v0.4.0 only works from this version onwards.  You can try installing an older version.

**Comment by johannbrink** [comment]
Hi Werner, yes talk about edge case... Yes I am on the latest version 2022.7.3

This is the result from https://loadshedding.eskom.co.za/:
HttpStatus: 200
Body: 
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 5127292777922526773<br><br><a href='[javascript:history.back();](about:blank)'>[Go Back]</a></body></html>

Would be nice if someone could proxy it for external users.

**Comment by wernerhp** [comment]
It's like Eskom doesn't want the world to know what's going on here...

**Comment by wernerhp** [comment]
You could setup HA for your family members 😉 and try something like https://github.com/custom-components/remote_homeassistant or expose it as a rest sensor https://www.home-assistant.io/integrations/rest/

**Comment by wernerhp** [comment]
Please try [v1.0.0](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.0.0)

**Comment by johannbrink** [comment]
Hi Werner, that works from down under. Thanks so much!
