### ISSUE TITLE
City of Tshwane

### ISSUE THREAD

**Issue by Jacquedebie** [wernerhp/ha.integration.load_shedding#18]
Hi, when I'm trying to add Load Shedding to HA it pops up the configuration where I need to search for my suburb.
![image](https://user-images.githubusercontent.com/26319787/178686360-02d1e5ad-ef06-4344-b46d-56709ff19599.png)
When I search for my Suburb (Villeria in Pretoria) it doesn't pick it up.

It only show these results.
![image](https://user-images.githubusercontent.com/26319787/178686760-ba810a01-7172-474a-b61a-df076fa3d82e.png)

Is there any place where I can Edit the Suburb id in code? To use my Suburb ID? Or am I using this wrong?
http://loadshedding.eskom.co.za/LoadShedding/GetSurburbData/?pageSize=1000000&pageNum=1&searchTerm=Villeria&id=167
{
    "Results": [
        {
            "id": "1027184",
            "text": "Villeria",
            "Tot": 0
        }
    ],
    "Total": 1
}

Thx

**Comment by wernerhp** [comment]
No guarantees when that will happen though.  Happy to accept pull requests.

**Comment by Pho3niX90** [comment]
I would be willing to add a $20 bounty on this, as I don't do python

**Comment by wernerhp** [comment]
Did some work on using EskomSePush API this weekend. Just need to clean things up a bit.

**Comment by Pho3niX90** [comment]
> Did some work on using EskomSePush API this weekend. Just need to clean things up a bit.

That is good news! I have tried all of the possible combinations of the other providers, and there is always a deviation from the actual pretoria schedules. 

My alternative was just to get a loadshedding sensor, but prefer a software solution.

**Comment by wernerhp** [comment]
[ v0.6.0-dev (Pre-release) - Feedback](https://github.com/wernerhp/ha.integration.load_shedding/issues/28)

**Comment by wernerhp** [comment]
Please try [v1.0.0](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.0.0)

**Comment by wernerhp** [comment]
@Pho3niX90 Please try [v1.0.0](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.0.0)

**Comment by McGuywer** [comment]
I have installed this addon, I am also in Villieria, Pretoria.
It works correctly now.

**Comment by Jacquedebie** [comment]
Works like a charm thx a lot!
