### ISSUE TITLE
cannot import name 'FlowResultType'

### ISSUE THREAD

**Issue by WarrenFoxley** [wernerhp/ha.integration.load_shedding#19]
**What is the Issue?**
When tyring to add the loadshedding integration via the mobile app or web, I am presented with the below screenshot.

![image](https://user-images.githubusercontent.com/7962113/178788563-8dfb0aaa-57fb-42c6-923a-6724311d9f1f.png)

Text: 
```
Error
This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant.
```

Upon checking the logs, I find the following log:

![image](https://user-images.githubusercontent.com/7962113/178788771-73eaab73-977b-4cd1-b824-3056756898e7.png)

Text: 
```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 12 July 2022 at 21:52:22 (7 occurrences)
Last logged: 18:52:15

Error occurred loading configuration flow for integration load_shedding: cannot import name 'FlowResultType' from 'homeassistant.data_entry_flow' (/usr/src/homeassistant/homeassistant/data_entry_flow.py)
```

Version:
Home Assistant Core 2022.6.6

**Comment by wernerhp** [comment]
Thanks for reporting @WarrenFoxley .   
With the v0.4.0 I updated from a [deprecated](https://developers.home-assistant.io/blog/2022/06/07/dataflow-constants-deprecation?_highlight=flowresulttype) `RESULT_TYPE_SHOW_PROGRESS_DONE` const to `FlowResultType`, which was introduced in the latest Home Assistant `2022.7.0`.  Unfortunately I forgot to update the minimum version number in HACS.  Upgrading Home Asisstant to 2022.7.0+ should fix this.

**Comment by wernerhp** [comment]
Pushed a new v0.4.0 tag.  Hopefully this will prevent anyone with older versions of HA from installing in HACS. 🤞

**Comment by WarrenFoxley** [comment]
Thanks, @wernerhp - updating to the latest Home Assistant worked a treat! :D
