### ISSUE TITLE
Stage not changing

### ISSUE THREAD

**Issue by molesza** [wernerhp/ha.integration.load_shedding#21]
Last few days the stage is stuck at 4 in home assistant. Not sure it is an issue or problem on my side. Currently running 0.4.1

**Comment by wernerhp** [comment]
Please send logs

**Comment by grahambrown11** [comment]
After some further investigation I found I was on `v0.2.0-alpha` (for some reason HACS was not showing the integration needed updating) I am now on `v0.4.1`
I had to delete the cache files as mentioned in the v0.2.0-alpha release and reinstall the integration.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/771817/180419293-46d445e5-18bd-4cbb-8660-2b3f95b02eb7.png">
However `schedule_stage` attribute of the Area entity seems to default to `Stage 4` when the state is `Off`

**Comment by wernerhp** [comment]
The area sensor defaults to Stage 4 when there is no load shedding, because there is no schedule for no load shedding.  Getting the future planned stages is a work in progress. You can try the latest master if you're want to try the latest.

**Comment by wernerhp** [comment]
Please try [v1.0.0](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.0.0)

**Comment by grahambrown11** [comment]
Ooo, thanks @wernerhp, this is going to be a game changer now that its using ESP...
Unfortunately my area sensor is not loading... it stays unavailable and in the logs I see errors:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/load_shedding/sensor.py:624
Integration: Load Shedding (documentation, issues)
First occurred: 2:24:14 PM (22 occurrences)
Last logged: 2:45:14 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/load_shedding/sensor.py", line 493, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 574, in _async_write_ha_state
    attr.update(self.extra_state_attributes or {})
  File "/config/custom_components/load_shedding/sensor.py", line 485, in extra_state_attributes
    self._attrs.update(clean(data))
  File "/config/custom_components/load_shedding/sensor.py", line 624, in clean
    if data[key] == value:
KeyError: 'stage'
```
Future improvement would be nice if there was a configure button to update the settings and other integrations have a reload option, so I dont have to restart my entire ha in order to reload the integration... not sure why your one is missing that option, maybe you have to implement a function for that to appear

**Comment by wernerhp** [comment]
Thanks for letting me know @grahambrown11 .  Added an additional check which I'll release shortly.  Unable to test right now, because of a problem with my API key.

I've looked at a Configure button to add / remove areas.  I'll look into the Reload option.  Not sure what's needed for that to work 😁

**Comment by grahambrown11** [comment]
Thanks @wernerhp 1.0.1 is working, the area sensor has state 🎉
