### ISSUE TITLE
Times off by two hours. 

### ISSUE THREAD

**Issue by Capone1983** [wernerhp/ha.integration.load_shedding#24]
Hi

Times are off by two hours, unless I am doing something wrong. HA time zone is set to (GMT+02:00) Johannesburg

![Capture](https://user-images.githubusercontent.com/36191570/190377634-cfffe8a5-9b03-4547-a849-82bef2caa8f8.PNG)
![Capture1](https://user-images.githubusercontent.com/36191570/190377656-dbeee02b-c8cc-4e97-88a9-00068785ecfe.PNG)

**Comment by tinuva** [comment]
Times look correct to me. The 2 hour difference you see, is because the entity is showing UTC times. 

2022-09-16T00:00:00 is UTC time format. It even shows this by appending the +00:00 at the end. You need to add 2 hours to get the SAST / South African timezone time. SA is UTC+2.

**Comment by Capone1983** [comment]
But if the time is returned from eskom as UCT+2 
Why have the entity as UCT? 

If the time returns from Eskom as UCT then forget the above. :)

**Comment by wernerhp** [comment]
Eskom returns it in GMT+2 but HA uses UTC in the sensor attributes (see `sun.sun`). Should show correctly when using `as_local` in templates

https://www.home-assistant.io/docs/configuration/templating/#time
