### ISSUE TITLE
No longer getting Schedules

### ISSUE THREAD

**Issue by DravenSA** [wernerhp/ha.integration.load_shedding#25]
This no longer shows me schedule, I says we are on stage 4, so that is still working, but when i look at the schedule, it is blank

I have 1 Device with 2 Entitles the Stage entity and the area entity, but the area entity shows this
"This entity is no longer being provided by the load_shedding integration. If the entity is no longer in use, delete it in settings."

Is this to do with HA update, or has something changed from where it pulls its information?

**Comment by ChristoffBo** [comment]
Same issue on two HA instances I manage

**Comment by DieMeesterAGL** [comment]
Same issue on my HA instance, tried to upgrade to 0.5.0.  Removed and readded integration.

![image](https://user-images.githubusercontent.com/105390044/190509139-f2bef777-e98a-4648-b18a-e90c144c3abd.png)


`2022-09-15 22:47:19.833 WARNING (MainThread) [homeassistant.components.rest.sensor] JSON result was not a dictionary or list with 0th element a dictionary
2022-09-15 22:47:28.003 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 151, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/config/custom_components/load_shedding/sensor.py", line 275, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/config/custom_components/load_shedding/sensor.py", line 216, in native_value
    start_time = datetime.fromisoformat(schedule[0].get(ATTR_START_TIME))
IndexError: list index out of range`

**Comment by uncappedshady** [comment]
Experiencing the same issue on my end. I see EskomsePush now as a personal API available - https://documenter.getpostman.com/view/1296288/UzQuNk3E

**Comment by rob196** [comment]
FYI - I got schedules back about an hour ago

**Comment by uncappedshady** [comment]
> FYI - I got schedules back about an hour ago

I can confirm, my schedules are working again also. Thank you for fixing the issue.

**Comment by ChristoffBo** [comment]
Stopped working again schedules are missing

**Comment by DieMeesterAGL** [comment]
The issue is not the integration, but the https://loadshedding.eskom.co.za/LoadShedding/GetScheduleM/1023281/2/166/700 API endpoint.  As per @uncappedshady I requested a personal API Token from EskomSePush guys and was able to get my schedules that way.  Hopefully @wernerhp will do another amazing integration for us.

**Comment by Mrmuttley** [comment]
Hi @wernerhp 
As per mentioned in the Automation Ideas page (apologies for this), I can't seem to get area specific info:

![LS Area](https://user-images.githubusercontent.com/50801967/190872240-2fe3400a-ce4b-4c2c-aa0d-88dfe3e69a32.jpg)

dashboard:
![image](https://user-images.githubusercontent.com/50801967/190872263-2037bdc7-57cb-4cfb-8766-d8e60be448af.png)

logbook:
![image](https://user-images.githubusercontent.com/50801967/190872294-36c85a7a-f024-426a-b82c-d2d961958349.png)

**Comment by wernerhp** [comment]
I'm working on adding ESP.   The library work is done, but need to finish up the HA integration.  Out of town for the next two weeks, so might still be a while.

**Comment by Mrmuttley** [comment]
> I'm working on adding ESP. The library work is done, but need to finish up the HA integration. Out of town for the next two weeks, so might still be a while.

Thanks so much :)

**Comment by wernerhp** [comment]
@Mrmuttley Settings > System > Logs then filter by load_shedding. Click each item to show the full message

**Comment by Mrmuttley** [comment]
> @Mrmuttley Settings > System > Logs then filter by load_shedding. Click each item to show the full message

022-09-17 20:40:04.287 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform load_shedding
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
state = self._stringify_state(available)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
value = self.native_value
File "/config/custom_components/load_shedding/sensor.py", line 192, in native_value
start_time = datetime.fromisoformat(schedule[0].get(ATTR_START_TIME))
IndexError: list index out of range

**Comment by wernerhp** [comment]
Try deleting the `.cache` folder (you can do this from Studio Code Server addon)

**Comment by wernerhp** [comment]
![Screenshot_20220917-213802~2](https://user-images.githubusercontent.com/2578772/190873840-8c087ee3-0deb-4ec8-808d-1dafbd8cd09e.png)

**Comment by DieMeesterAGL** [comment]
This solved my issue, data updating again:

> See [#21 (comment)](https://github.com/wernerhp/ha.integration.load_shedding/issues/21#issuecomment-1192435859)
> 
> Try deleting the `.cache` folder (you can do this from Studio Code Server addon) and reload the integration.
> 
> ![Screenshot_20220917-213802~2](https://user-images.githubusercontent.com/2578772/190873840-8c087ee3-0deb-4ec8-808d-1dafbd8cd09e.png)

I did not need to reinstall, just called the update entity service under **Developer Tools** > **SERVICES**
```
service: homeassistant.update_entity
data: {}
target:
  entity_id: sensor.load_shedding_orange_farm_ext_1
```

**Comment by Mrmuttley** [comment]
Thanks @wernerhp 
Trying this now

**Comment by Mrmuttley** [comment]
@wernerhp 
me again :(

Not sure if I'm being doff or it's something obvious but I've copied your card config and updated it with my area - it's only showing an on/off state - not actual time of the load shedding or the time left like yours does..

`type: entities
entities:
  - type: custom:multiple-entity-row
    icon: mdi:lightning-bolt-outline
    name: Status
    entity: sensor.load_shedding_stage
    active: '{{ not is_state("sensor.load_shedding_stage", "No Load Shedding") }}'
    state: '{{states("sensor.load_shedding_stage")}}'
  - type: custom:multiple-entity-row
    icon: mdi:timer-outline
    name: Sandown
    active: '{{ states("sensor.load_shedding_sandown_ext_10") == "on" }}'
    state: >-
      {{ (state_attr("sensor.load_shedding_sandown_ext_10", "start_time") |
      as_datetime | as_local).strftime("%H:%M") }}  -  {{
      (state_attr("sensor.load_shedding_milnerton", "end_time") | as_datetime |
      as_local).strftime("%H:%M") }}
    secondary: >-
      {% if states("sensor.load_shedding_sandown_ext_10") == "off" %} Starts in
      {{ timedelta(minutes=state_attr("sensor.load_shedding_sandown_ext_10",
      "starts_in")) }} {% else %}  Ends in {{
      timedelta(minutes=state_attr("sensor.load_shedding_sandown_ext_10",
      "ends_in")) }} {% endif %}
    entity: sensor.load_shedding_sandown_ext_10
state_color: true`

This is the result I'm getting:
![image](https://user-images.githubusercontent.com/50801967/190875386-51acfa66-2993-4cf8-9bf7-35274543994e.png)

**Comment by uncappedshady** [comment]
In the meantime I have changed my strategy until this integration is stable again. If anyone else needs a solution for right now you could use the following:
https://github.com/beyarkay/eskom-calendar

I have this setup in my Google Calendar and added Google Calendars to Home Assistant. I had to create a few value templates for the time until loadshedding and time until it ends but it is working great. I will keep watching this space to see once this integration is stable again.

Here is a screenshot of my loadshedding setup:
![image](https://user-images.githubusercontent.com/20617622/190875537-cbae0227-254d-4760-ade4-d0798fbb2499.png)

**Comment by Mrmuttley** [comment]
Hi @wernerhp 
I've noticed that the integration "time left" seems to get stuck when the load shedding schedules change. Load shedding is meant to start at 22:00 but as per the screenshot below, there's only 39 minutes of load shedding left..  

![image](https://user-images.githubusercontent.com/50801967/191352353-e20ee106-6c4e-4be8-960f-d01dd5812a2f.png)

Here's the log:
This error originated from a custom integration.

Logger: custom_components.eskom_loadshedding
Source: helpers/update_coordinator.py:151
Integration: Eskom Loadshedding Interface (documentation, issues)
First occurred: September 19, 2022 at 20:42:15 (1 occurrences)
Last logged: September 19, 2022 at 20:42:15

Error fetching eskom_loadshedding data: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://loadshedding.eskom.co.za/LoadShedding/GetStatus')

Thanks as always for the awesome work done on this - the family and I really appreciate it :)

**Comment by Beylie** [comment]
> In the meantime I have changed my strategy until this integration is stable again. If anyone else needs a solution for right now you could use the following: https://github.com/beyarkay/eskom-calendar
> 
> I have this setup in my Google Calendar and added Google Calendars to Home Assistant. I had to create a few value templates for the time until loadshedding and time until it ends but it is working great. I will keep watching this space to see once this integration is stable again.
> 
> Here is a screenshot of my loadshedding setup: ![image](https://user-images.githubusercontent.com/20617622/190875537-cbae0227-254d-4760-ade4-d0798fbb2499.png)

Would you please share your value templates on your website? Using HA but value templates are still above my paygrade. Sorry for asking in this thread. Could not find any other way to contact you.

**Comment by wernerhp** [comment]
> 

Value templates are in the Automation Examples in the README.md file in this repo.

**Comment by DravenSA** [comment]
After updating to the new HA 2022.9.7 again the integration is not showing values. 
I never know if it Eskom API or the updates that break this

**Comment by wernerhp** [comment]
> After updating to the new HA 2022.9.7 again the integration is not showing values. I never know if it Eskom API or the updates that break this

Check the logs. Post them here  
If you see 
```
File "/config/custom_components/load_shedding/sensor.py", line 192, in native_value
start_time = datetime.fromisoformat(schedule[0].get(ATTR_START_TIME))
IndexError: list index out of range
```
Delete the /config/.cache folder
Otherwise it might be Eskom doing something and should reaolve in a few hours.

**Comment by DravenSA** [comment]
Here is the last log

```
Logger: homeassistant.components.sensor
Source: custom_components/load_shedding/sensor.py:216
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:54:36 (2 occurrences)
Last logged: 10:54:37

Error adding entities for domain sensor with platform load_shedding
Error while setting up load_shedding platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/config/custom_components/load_shedding/sensor.py", line 216, in native_value
    start_time = datetime.fromisoformat(schedule[0].get(ATTR_START_TIME))
IndexError: list index out of range
```

Hope this helps

I did Delete the /config/.cache folder, but it didnt help

**Comment by wernerhp** [comment]
Hmm, that's weird. Deleting the cache folder and reloading the integration usually fixes that issue (which was due to a missing migration from one version to another).  What version of the integration are you using and what area are you in?

**Comment by DravenSA** [comment]
I am using v0.5.0
I am in Randburg (2) City of Joburg, but i found that the allermansdrift in the freestate runs the same schedule and is part of the loadshedding.eskom.co.za So I have been using that.

If there is a way to intergrate Randburg, I will gladly use it.

**Comment by wernerhp** [comment]
[ v0.6.0-dev (Pre-release) - Feedback](https://github.com/wernerhp/ha.integration.load_shedding/issues/28)

**Comment by wernerhp** [comment]
[v1.0.0](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.0.0)
