### ISSUE TITLE
Area 7 Sea Point, Cape Town off by 1 stage level

### ISSUE THREAD

**Issue by zeane** [wernerhp/ha.integration.load_shedding#27]
This integration unfortunately appears to be showing the wrong Stage level, (ever since I installed it).

![IMG-20220926-WA0000](https://user-images.githubusercontent.com/40634267/192325103-31f290a4-ac75-4728-a03d-4291ead297eb.jpg)
![Screenshot_20220926-175054](https://user-images.githubusercontent.com/40634267/192325118-9c19e6bc-daf8-44c1-89da-0a8eb2f110ba.jpg)

**Comment by wernerhp** [comment]
Please try https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.0.0

**Comment by wernerhp** [comment]
@zeane any feedback?
