### ISSUE TITLE
Display Card Yaml file mixup

### ISSUE THREAD

**Issue by DravenSA** [wernerhp/ha.integration.load_shedding#30]
Not an issue with the actual integration, 
but yothe Code for the cards, the links are not right, 
Card 1 is linked to card2.yaml
Card 2 is linked to card3.yaml
Card 3 is linked to card2.yaml

I am sure other will work it out, but i did take a few minutes.,
Also, some people might not realise that Mushroom cards are need as in card as it only says
I created this card with the help of [template-entity-row]

Also noticed tha Image for Card 2 and the code for card 2 dont match as there is nothing in there about National stage or cape town stage. I am not a coder, but i am sure i can fumble my way around to get that info to work, just always concerned for others that only know how to copy and paste.

Everything so far seems to be working like a dream, So happy that the API became so much easier to get

Great job

**Comment by wernerhp** [comment]
https://github.com/wernerhp/ha.integration.load_shedding/commit/82e5b96196e9f97e31add733f18fff63ad5ad898

**Comment by DravenSA** [comment]
Sorry, I was talking about here

https://github.com/wernerhp/ha.integration.load_shedding/blob/v1.0.0/README.md
