### ISSUE TITLE
End time truncated to midnight

### ISSUE THREAD

**Issue by asifkassam** [wernerhp/ha.integration.load_shedding#32]
Hi Werner,

Great effort and integration - works great so far.

I have noticed however, that for loadshedding that spans across midnight, the end time is truncated to midnight - please see below - correct endtime is 01:30 the next day - is this a problem with the API?

![image](https://user-images.githubusercontent.com/67918736/199031099-2aa6fa9d-0092-41b4-9371-254676128fd2.png)

**Comment by wernerhp** [comment]
This is an issue in the Eskom SePush API.  I've reported it to them.

**Comment by asifkassam** [comment]
I've installed the latest dev release - i'll give you some feedback when i have a loadshedding stage over midnight
