### ISSUE TITLE
Time to LS not showing Bordeaux (14)

### ISSUE THREAD

**Issue by JayMcG** [wernerhp/ha.integration.load_shedding#36]
Hi, forgive me if this is the wrong place to post this....

I loaded my area, Bordeaux South, Block 14. Unfortunately, it doesn't show any times other than the stage. Am I missing something? 

Thanks for making this! 

![Capture](https://user-images.githubusercontent.com/17012684/199810768-d5f078b1-6a1c-4202-9ef0-35a0b3d57673.JPG)

**Comment by gregcsw** [comment]
Click on your area and then open the attributes.

There are also examples of cards in the documentation to display the information.

![Screenshot 2022-11-03 at 18 54 44](https://user-images.githubusercontent.com/43892478/199826743-acf91c3c-5f46-4cfc-b653-63107447a900.png)

**Comment by JayMcG** [comment]
> Click on your area and then open the attributes.
> 
> There are also examples of cards in the documentation to display the information.
> 
> ![Screenshot 2022-11-03 at 18 54 44](https://user-images.githubusercontent.com/43892478/199826743-acf91c3c-5f46-4cfc-b653-63107447a900.png)

Magic! Thanks so much!

**Comment by wernerhp** [comment]
Check out the example [Cards](https://github.com/wernerhp/ha.integration.load_shedding#cards) and [Automations](https://github.com/wernerhp/ha.integration.load_shedding#automation-ideas) in the readme
