### ISSUE TITLE
Time -1h Difference

### ISSUE THREAD

**Issue by paulbalinnel** [wernerhp/ha.integration.load_shedding#37]
Hi Werner, any advice on why the time is out by -1h on my calendar and LS integration, whilst EskomSePush its correct?
<img width="437" alt="Screenshot 2022-11-05 at 06 38 10" src="https://user-images.githubusercontent.com/89601096/200101387-6cf70e36-1647-4ce5-a703-5dbd68a2fdd3.png">
<img width="440" alt="Screenshot 2022-11-05 at 06 38 03" src="https://user-images.githubusercontent.com/89601096/200101390-c9e401b1-7c5d-45fc-bd0d-81b486862efd.png">
<img width="528" alt="Screenshot 2022-11-05 at 06 40 50" src="https://user-images.githubusercontent.com/89601096/200101427-94d582f3-6377-40fe-bd2b-8a8af9c44723.png">

**Comment by wernerhp** [comment]
What's your Time Zone under Settings > System >General?

<img width="608" alt="image" src="https://user-images.githubusercontent.com/2578772/200185213-1cf33d16-17f8-45dc-a513-90d4040966b7.png">

**Comment by paulbalinnel** [comment]
Hallo, yes I did check that the time zone was set correct. thought it mite be that or even a daylight savings issue, but nope my time zone is set GMT+2

**Comment by wernerhp** [comment]
Hmm...curious...

**Comment by wernerhp** [comment]
Where do those emojis come from and are some times `24:00-24:30` and `04:00-04:59`?  Super weird.

<img width="343" alt="image" src="https://user-images.githubusercontent.com/2578772/200427449-7d385921-458d-4062-84b5-0040b2598d5d.png">

Please send screenshots of the area sensor's attributes in the Developer Tools and updated and include the sensor name please.

**Comment by paulbalinnel** [comment]
hallo, appreciate your help!!!

<img width="1043" alt="Screenshot 2022-11-08 at 07 10 30" src="https://user-images.githubusercontent.com/89601096/200480368-e3009a5f-d81c-48cc-b1d0-ac0376e92642.png">

**Comment by paulbalinnel** [comment]
Hi Werner, if I load a different area, same time slots, it shows the correct time.

**Comment by wernerhp** [comment]
@paulbalinnel The issue does appear to be with the area you've selected.

I notice on the Eskom SePush app there are both **Saint Francis Bay (16)** and **St Francis Bay (16)**.  It seems like you may have selected the former in your ESP app and the latter in the HA integration.  When selecting the latter in the app, the times matches those in the sensor screenshot.

<img src="https://user-images.githubusercontent.com/2578772/200493879-6fedcd2a-679f-492a-bae3-5d361c5d4791.png" width="25%"/><img src="https://user-images.githubusercontent.com/2578772/200493891-3dcdb9bc-2dfd-4689-8c61-a0f8049eda1b.png" width="25%"/><img src="https://user-images.githubusercontent.com/2578772/200493918-de50c133-699e-4259-aafd-649fa7da0e17.png" width="25%"/>

I can't explain the those strange `24:00-24:30` and `04:00-04:59` times or the emojis you had.  Maybe it was in the data.

**Comment by paulbalinnel** [comment]
Thank You!!! all working. Really appreciate your integration!

**Comment by wernerhp** [comment]
You are welcome.

Please consider [buying me a coffee](https://github.com/wernerhp/ha.integration.load_shedding#support) to support my work.
