### ISSUE TITLE
calendar.load_shedding_forecast not updating

### ISSUE THREAD

**Issue by DravenSA** [wernerhp/ha.integration.load_shedding#38]
So i noticed the other day that using the calendar.load_shedding_forecast, that it was not updating the information.
first thing i did was restart HA, and it worked, but then it didn't update again when thing changed. So i Reloaded the integration, and that worked, so i left it overnight in case it was a daily thing, and noticed that it still didn't update, so i reload the integration again , but when i didn it all broke ( I am sure it all broke because load sheading has now been suspended)

So here are some screenshots. Hope they help

Working as intended during a loadshedding session
![Screenshot_20221106-021243_Home Assistant](https://user-images.githubusercontent.com/25724682/200165482-d58cc2f2-b45a-4f2b-b20e-6f38fc5455e3.jpg)

Top information still there, after load shedding ended
![Screenshot_20221106-023203_Home Assistant](https://user-images.githubusercontent.com/25724682/200165513-870702b2-a8bb-444a-ac02-e3be7c74878d.jpg)

After a restart or an integration reload, greyed out area disappeared
![Screenshot_20221106-023308_Home Assistant](https://user-images.githubusercontent.com/25724682/200165544-52333e71-54f2-4987-a2c2-0389b319bbfe.jpg)

many hours later greyed out area back again after load shedding fished
![Screenshot_20221106-121136_Home Assistant](https://user-images.githubusercontent.com/25724682/200165576-fff06077-7183-49a7-846b-20dbdd18ef25.jpg)

Broke calendar after a reload and load shedding suspended. 
![Screenshot_20221106-121942_Home Assistant](https://user-images.githubusercontent.com/25724682/200165616-1f5565a9-5fa8-4a72-8bc3-5c66eb32488e.jpg)

Hope this helps, or someone can point me in the correct direction for a solution

**Comment by wernerhp** [comment]
Thanks.  I also noticed the calendar not updating.  Should be fixed in the next `dev.2` release.

**Comment by wernerhp** [comment]
>_but when i didn it all broke ( I am sure it all broke because load sheading has now been suspended)_


<img width="535" alt="Screenshot 2022-11-06 at 17 26 37" src="https://user-images.githubusercontent.com/2578772/200179532-3673022b-6ac4-4d71-bf07-4d00f1705c0c.png">

<img width="767" alt="Screenshot 2022-11-06 at 17 26 22" src="https://user-images.githubusercontent.com/2578772/200179534-51707795-c0f7-4c95-8930-6abf5e6c0b94.png">

This might be something in the `yaml` code of your Mushroom Chip's template.
I notice the Stage is `Unknown`.  Might be related 🤔  Please send the sensor attributes from Developer Tools when this is for when the stage is `Unknown`.

**Comment by DravenSA** [comment]
I believe it is because the Stage was Unknown. Everything is working again when it sees the stage as No Load Shedding

Look like this , (BEFORE Update to v1.1.0-dev.2)

![Screenshot_20221106-205951_Home Assistant](https://user-images.githubusercontent.com/25724682/200189836-66a77ea1-2aee-4b2b-8778-366ba06f2991.jpg)

my code
```
type: vertical-stack
cards:
  - type: custom:mushroom-chips-card
    chips:
      - type: entity
        entity: sensor.date_time
      - type: entity
        entity: sensor.load_shedding_stage_eskom
        icon: ''
      - type: template
        content: >-
          Next Stage {{ state_attr("sensor.load_shedding_stage_eskom",
          "next_stage") }} {{ state_attr("sensor.load_shedding_stage_eskom",
          "next_start_time") | as_timestamp(next_start_time) |
          timestamp_custom("%H:%M", True)}}
      - type: template
        content: >-
          {{state_attr(entity, "count")}}/{{state_attr(entity, "limit")}} - Last
          Updated  ({{state_attr(entity, "last_update") | as_timestamp |
          timestamp_custom("%H:%M", True)}})  -  Next Update
          ({{(state_attr(entity, "last_update") | as_timestamp + (90*60))|
          timestamp_custom("%H:%M", True)}})
        entity: sensor.load_shedding_sepush_api_quota
        icon: mdi:api
        tap_action:
          action: more-info
      - type: entity
        entity: sensor.load_shedding_area_jhbcitypower2_2_greymont
    alignment: center
  - type: custom:atomic-calendar-revive
    enableModeChange: true
    firstDayOfWeek: 1
    maxDaysToShow: 7
    refreshInterval: 1800
    entities:
      - calendar.load_shedding_forecast
    showCurrentEventLine: false
    showMonth: true
    showWeekDay: true
    disableEventLink: true
    showNoEventsForToday: false
    disableLocationLink: true
    showFullDayProgress: false
    showEventIcon: false
    showHiddenText: false
    showCalendarName: false
    calShowDescription: false
    showLastCalendarWeek: false
    disableCalEventLink: true
    disableCalLocationLink: true
    disableCalLink: true
    showDescription: false
    dateFormat: LL
    showDate: false
    sortByStartTime: false
    showRelativeTime: true
    showProgressBar: true
    showLocation: true
  - type: markdown
    content: >
      {% set stage_sensor = "sensor.load_shedding_stage_eskom" %}  {% set
      area_sensor = "sensor.load_shedding_area_jhbcitypower2_2_greymont" %} {%
      set start_time = state_attr(stage_sensor, "start_time") %}    {% set
      end_time = state_attr(stage_sensor, "end_time") %} {% set area_schedule =
      state_attr(area_sensor, "forecast") %} 

      {% if area_schedule %}
        {% set start_time = area_schedule[0].start_time %}
        {% set end_time = area_schedule[0].end_time %}
        
        {% if is_state(area_sensor, "off") %}
          {% set starts_in = timedelta(minutes=state_attr(area_sensor, "starts_in")).total_seconds() | int // 60 %}
          {% set mins = starts_in % 60 %}
          {% set hrs = starts_in // 60 % 24 %}
          {% set days = starts_in // 1440 %}
          {% set alert = "Load Shedding starts in {d}d {h}h {m}m ({next})".format(d=days, m=mins, h=hrs, next=as_timestamp(start_time) | timestamp_custom("%H:%M", True)) %} 

          {% if is_state_attr(stage_sensor, "stage", 0) %}
            <ha-alert alert-type="success">{{ states(stage_sensor) }}</ha-alert>
          {% elif starts_in > 1440  %}
            <ha-alert alert-type="success">{{ alert }}</ha-alert>
          {% elif not is_state_attr(stage_sensor, "stage", 0) and 60 < starts_in <= 1440 %}
            <ha-alert alert-type="warning">{{ alert }}</ha-alert>
          {% else %}
            <ha-alert alert-type="error">{{ alert }}</ha-alert>
          {% endif %}
        {% else %}
          {% set ends_in = timedelta(minutes=state_attr(area_sensor, "ends_in")).total_seconds() | int // 60 %}   
            {% set mins = ends_in % 60 %}        
            {% set hrs = ends_in // 60 % 24 %}
            {% set days = ends_in // 1440 %}
            {% set alert = "Load Shedding ends in {d}d {h}h {m}m ({next})".format(d=days, m=mins, h=hrs, next=as_timestamp(end_time) | timestamp_custom("%H:%M", True)) %} 

            <ha-alert alert-type="error">{{ alert }}</ha-alert>
        {% endif %}
      {% endif %}

```

And still looks the same after the update. 

Definitely something to do with Unknown.

**Comment by DravenSA** [comment]
Also just noticed, forecast not showing that there will be loadsheding from 16.00 tomorrow.
But it says no events in the next few days
Hope im not causing problems
![Screenshot_20221106-232216_Home Assistant](https://user-images.githubusercontent.com/25724682/200196000-2bbc5f56-90bf-4718-a035-01f4288f6a77.jpg)

**Comment by wernerhp** [comment]
The lack of forecast data is Eskom SePush not returning more data on their API a th this time.  I've noticed the same in the app.

**Comment by wernerhp** [comment]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/2578772/200252904-8e5b424c-3a92-48bc-9879-40b0353ddaa1.png"> - [Source](https://zatech.slack.com/archives/C043YCM6BRS/p1667806729767659?thread_ts=1667806255.881409&cid=C043YCM6BRS)

**Comment by DravenSA** [comment]
I have looked into the States, and it shows information, so the reason it is not showing on the fronned end is lack of my knowledge of making templets.
I am sure the Calendar template is the problem, in STATES it shows
[calendar.load_shedding_forecast]
```
message: Stage 2
all_day: false
start_time: 2022-11-07 16:00:00
end_time: 2022-11-07 18:30:00
location: Greymont (2)
description: Load Shedding
friendly_name: Load Shedding Forecast
```
in the area it shows
[sensor.load_shedding_area_jhbcitypower2_2_greymont]
```
stage: 0
start_time: 0
end_time: 0
ends_in: 0
starts_in: 371
next_stage: 2
next_start_time: 2022-11-07T14:00:00+00:00
next_end_time: 2022-11-07T16:30:00+00:00
forecast: 
- stage: 2
  start_time: '2022-11-07T14:00:00+00:00'
  end_time: '2022-11-07T16:30:00+00:00'
- stage: 2
  start_time: '2022-11-08T14:00:00+00:00'
  end_time: '2022-11-08T16:30:00+00:00'

last_update: 2022-11-07T07:03:14+00:00
attribution: Data provided by sepush.co.za
icon: mdi:calendar
friendly_name: Greymont (2)
```

So all the information is there, it is just not pulling through correctly to the front to make the template more informative.

I am sure once we are in Loadshedding all the information will be there,

This is so difficult to explain.
I really appreciate all your time and work on this, I wish i was better at building templates

**Comment by wernerhp** [comment]
@DravenSA The calendar entity only uses the forecast for the area sensors, so if there's no event data for the area for then next 48 hours then it won't show anything.  
Having said that, it looks like the calendar entity is still not refreshing properly when the data is updated.  Will look into this again.  If you reload the integration from the UI now, the calendar should show the forecast for your area as per your post above.

**Comment by DravenSA** [comment]
Yes a reload of the integration did in fact pull new information. The sad thing is everytime a reload or a restart on HA it uses 2 API allocations :-(

also nice to know that is is not just my bad template manipulation, and that there actually is something else. 

Out of curiosity, if the calendar is not updating automatically, would it be possible to the do a "reload" just before the API does a check?  or is that too much strain, and to much of a hit and a miss to be stable and solid enough?

**Comment by DravenSA** [comment]
So i took a screenshot before the reload, and one after the reload but fast forward an hour, i see that it has revered back to not showing data

Screen before Reload Time 10:34 API count 12/50

![Screenshot_20221107-103442_Home Assistant](https://user-images.githubusercontent.com/25724682/200278064-6c6540da-ff02-4e69-9819-70df740dcf08.jpg)

After Reload Time 10:35  API count 14/50

![Screenshot_20221107-103531_Home Assistant](https://user-images.githubusercontent.com/25724682/200278208-49476457-5072-4afb-b71c-d63c52b9ceec.jpg)

An hour later Time 11:39 API cout Still 14/50

![Screenshot_20221107-113912_Home Assistant](https://user-images.githubusercontent.com/25724682/200278485-ead9592e-3e25-4d4d-87b4-cf36a6c74551.jpg)

Hope this helps and that you dont feel i am being a pest
