### ISSUE TITLE
Add city power privider

### ISSUE THREAD

**Issue by boozelclark** [wernerhp/ha.integration.load_shedding#4]
Hi

If possible could you add city power as a schedule provider. Looks like the calendar on this site https://www.citypower.co.za/customers/Pages/Load_Shedding_Downloads.aspx
Uses an API where it could come from.

Thanks

**Comment by wernerhp** [comment]
This Home Assistant integration makes use of [this Python library](https://gitlab.com/wernerhp/load-shedding) I wrote which currently only scrapes data from loadshedding.eskom.co.za .  I've looked at the CityPower API, but it's quite a bit of work to add and don't have the time for this right now.  Would also need to refactor that lib a little to make it work.  It's open source so anyone can contribute to add other municipalities.  I have a colleague who looked into it a bit, so maybe something will come from it.  Feel free to create a Merge Request on that repo.

**Comment by wernerhp** [comment]
A work-around is to find an Eskom are with the same schedule as your area and use that.
https://github.com/wernerhp/ha_integration_load_shedding/issues/3#issuecomment-1122816596

**Comment by rob196** [comment]
Thanks @wernerhp , I have done the workaround and is looking good

Will also try look into the python library when (if) I have time

**Comment by Capone1983** [comment]
I think the workaround is not in sync any more. 
I was using paulshof ext 65 for Block 14. 

This time around times were off. 

@rob196 - Help us out here :)

**Comment by wernerhp** [comment]
Ah, sorry to hear that. Maybe a different one🤷‍♂️
EskomSePush API is out. I have started with integration. Needs a bit more work, but watch this space.

**Comment by Capone1983** [comment]
@wernerhp Being looking for the past hour for one that is the same, no luck. 
I will wait for the next version with integration to EskomSePush. 

Keep up the great work.

**Comment by rob196** [comment]
@Capone1983 thought that may happen (luckily for me still works), looking at their spreadsheet from [here](https://www.eskom.co.za/distribution/customer-service/outages/downloadable-loadshedding-spreadsheets-for-eskom-customers/) paulshof ext 65 is still Block 14, so not sure why its wrong now - very likely spreadsheet is outdated though

- I have heard that some areas have changed blocks (multiple times in a couple of weeks - think they back to their original block now)

@wernerhp awesome, looking forward to the EskomSePush version

**Comment by tinuva** [comment]
> Ah, sorry to hear that. Maybe a different one🤷‍♂️ EskomSePush API is out. I have started with integration. Needs a bit more work, but watch this space.

Hey, how far are you with this? Have you pushed the incomplete work to another branch on the https://gitlab.com/wernerhp/load-shedding/ somewhere yet?

**Comment by wernerhp** [comment]
[ v0.6.0-dev (Pre-release) - Feedback](https://github.com/wernerhp/ha.integration.load_shedding/issues/28)

**Comment by wernerhp** [comment]
Please try [v1.0.0](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.0.0)
