### ISSUE TITLE
Gets stuck with loadshedding

### ISSUE THREAD

**Issue by ChristoffBo** [wernerhp/ha.integration.load_shedding#41]
Works perfect.. Until loadshedding starts then the timer gets stuck have to restart hassio

**Comment by wernerhp** [comment]
Should be fixed in [1.1.0-dev.9](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.1.0-dev.9)

**Comment by wernerhp** [comment]
@ChristoffBo Please try the latest release.

**Comment by ChristoffBo** [comment]
Works perfectly thank you very much meneer
