### ISSUE TITLE
Load Shedding Stage Unknown 

### ISSUE THREAD

**Issue by JayMcG** [wernerhp/ha.integration.load_shedding#42]
Hi! 

I see that my load shedding stage has been unknown for a few days. The rest of the data seems to be updating just fine. 

Any ideas on how to fix this?

Thanks in advance!

![Capture](https://user-images.githubusercontent.com/17012684/201292572-7c6e0690-1dab-468f-861e-08ebc8739b29.JPG)

**Comment by hjpfourie** [comment]
Same happening my side. All other values updating and pulling through fine.

**Comment by ManishHira-Code** [comment]
Me too ...

**Comment by grahambrown11** [comment]
I see there is a dev release with a bunch of changes, I switched to give it a go and so far its working better.
Hopefully Werner gets to releasing it soon

**Comment by wernerhp** [comment]
Just released [v1.1.0-dev.9](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.1.0-dev.9).  Hopefully the last dev release.

**Comment by DravenSA** [comment]
I used to have this problem , but because we were constantly on Stage 2, it always showed as Unknown, but now that we have been informed for Stage 3 coming, It is working just fine with v1.1.0 release

![Screenshot 2022-11-14 152423](https://user-images.githubusercontent.com/25724682/201671840-6c53ab7a-20c1-4e3c-9e89-099e467bf956.jpg)

**Comment by JayMcG** [comment]
> Just released [v1.1.0-dev.9](https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.1.0-dev.9). Hopefully the last dev release.

Thanks for all your efforts! Working perfectly now.

**Comment by wernerhp** [comment]
✅ Fixed.
Please consider [buying me a coffee](https://github.com/wernerhp/ha.integration.load_shedding#support) to support my work.
