### ISSUE TITLE
Suburb load-shedding sensor always shows as unavailable.

### ISSUE THREAD

**Issue by Brumawen** [wernerhp/ha.integration.load_shedding#45]
My suburb's load-shedding sensor always shows as unavailable. 

![image](https://user-images.githubusercontent.com/8055524/206468281-32984b80-236d-4fe5-8a8e-64f996a1a020.png)

**Comment by wernerhp** [comment]
Looks like you upgraded from an old version to v1.1.0. Please see release notes. There was a breaking change.
Basically there will be a new sensor with a different name. If not you can just reconfigure the integration and it should sort you out.
https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.1.0

**Comment by Meyrcr** [comment]
Having the same issue with a new install:
![image](https://user-images.githubusercontent.com/36159335/212016754-565f5982-0f3b-48c1-be99-3d0303e1bedf.png)

I tried different Mangaung metro areas with the same outcome.
I do see the following errors:
![image](https://user-images.githubusercontent.com/36159335/212019519-7feb2d42-dcb2-47c6-b737-3a3112ec38bb.png)![image](https://user-images.githubusercontent.com/36159335/212019277-35299b21-99a4-46b1-9235-053c978925e0.png)

Please advise.

**Comment by wernerhp** [comment]
Please go to Developer Tools > States and filter Entity by `sensor.load_shedding`.  Then send screenshots of each of the entities.

**Comment by Meyrcr** [comment]
![image](https://user-images.githubusercontent.com/36159335/212029007-f60fb865-1322-402c-a7cb-2d0344bcced9.png)

**Comment by wernerhp** [comment]
and the one for your area (`westdene`)?

**Comment by wernerhp** [comment]
Looks like there maybe be an problem getting the area info from the ESP API.  I've [reported](https://zatech.slack.com/archives/C043YCM6BRS/p1673516549308179) to EskomSePush on their #eskomsepush Slack channel.

**Comment by Meyrcr** [comment]
> and the one for your area (`westdene`)?
Ons ESP app I use "showgrounds (1)", but "westene (1)" has the same schedule.
I thought the (1) at the end might be a problem, but looks like you found a error.
Thx for the assistance and great integration!

**Comment by wernerhp** [comment]
@dan from ESP pointed me to the fact that Mangaung only has 4 stages on the ESP API which may lead to issues with the way I calculate the forecast.  Will look into this.

**Comment by vNate007** [comment]
@wernerhp I have the same issue on a fresh install.... well, several, with restarts inbetween. 

![image](https://user-images.githubusercontent.com/99830370/215986427-2d6c046e-3bcf-4155-a56c-5297edcc736d.png)

So not seeing my area sensor at all but I have the entity. 

![image](https://user-images.githubusercontent.com/99830370/215986806-886d0600-7596-4ec8-b37a-f1d8abdc528b.png)

Do I need to do anythning or just wait for the API to pull itself towards itself?

**Comment by vNate007** [comment]
So by updating the Integration I get it to recoglnise the area but it does not show the stage, alwaus saus "off". I have left it alone for a night, reloaded a couple of times, deleted and reconfigured with different areas...  So the sensor state does not update. Some of the attributes do update though.  

![image](https://user-images.githubusercontent.com/99830370/216251514-5153fe01-0b6d-4eb9-bfa6-37416c21db6e.png)
