### ISSUE TITLE
Unable to add "Area" on new Integration setup - Full Details - Error seems to be persistent.

### ISSUE THREAD

**Issue by denzelm5** [wernerhp/ha.integration.load_shedding#53]
Home Assistant : VM
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

Log Relating to Integration :

Logger: homeassistant.helpers.template
Source: helpers/template.py:540
First occurred: 9:34:56 PM (17 occurrences)
Last logged: 9:49:56 PM

Template variable error: 'None' has no attribute 'eskom' when rendering '{{ state_attr('sensor.eskom_loadshedding_stage','status').eskom.stage}}'

Screen Shot :
![image](https://user-images.githubusercontent.com/57428868/215288268-eca5a927-83dc-4df0-a7af-7dcd9e793894.png)

Summary :
It accepts the API Token successful , at the screen where you have add in your area none of the parameter's work.

Regards
Denzel

**Comment by denzelm5** [comment]
Hi , This issue is now resolved as it was caused by a conflicting config relating to some custom settings.

**Comment by JayMcG** [comment]
I am having the same problem and cannot figure out where the issue is.

**Comment by denzelm5** [comment]
@JayMcG  can you post the related logs .

**Comment by JayMcG** [comment]
I added a logger and see that there was a suspected abuse so my account was blocked. Hoping it clears in a day or so.

**Comment by denzelm5** [comment]
I suspected this was the issue. So the API complains when there are more than one instance from the same ip address . I also have this issue as im running more than one instance of home assistant on my network . it clears every 24hours.

**Comment by wernerhp** [comment]
If you have more than one instance of HA on the same network, you should use the same API key.  EskomSePush blocks multiple API keys coming from the same IP.

**Comment by wernerhp** [comment]
Please post some logs `HA > Settings > System > Logs`

**Comment by JayMcG** [comment]
Update. Ok, everything has cleared again and is working properly. I was setting up an HA instance for a friend and used a different API key for his pi so that must have caused the issues.
