### ISSUE TITLE
Dashboard setup

### ISSUE THREAD

**Issue by Shaunpottie** [wernerhp/ha.integration.load_shedding#56]
Really nice, I just wish you guys had a tutorial on how to setup the dashboard for beginners that are only coming into home assistant now.

**Comment by wernerhp** [comment]
Did you have a look at the [README](https://github.com/wernerhp/ha.integration.load_shedding#readme) and [Example Cards](https://github.com/wernerhp/ha.integration.load_shedding/blob/master/examples/) ?

**Comment by milsky99** [comment]
Can someone assist, I have the basic card that is created with a new dash up and running but none of the others are working... it seems as if sensor names have been changed I noticed that in the example file it shows capetown yet the sensor is cape_town

The template-entity-row is not being found even thought these front end integrations have all been installed !! 

Has then HACS code been updated without the examples being updated, if this is the case is there any source for updated examples

Hugely appreciated and apologies for the moan but I dont have the skill to create the great cards that are already developed

**Comment by wernerhp** [comment]
Please post your code and screenshots of your sensors and logs
