### ISSUE TITLE
Loadshed times are off by 2 hours...

### ISSUE THREAD

**Issue by zs3y** [wernerhp/ha.integration.load_shedding#63]
I wonder whether I am the only one seeing my loadshed times off by two hours?

**Comment by tinuva** [comment]
I don't have this issue, and yes I am using this integration just fine.

If your times are off by 2 hours, first step is to confirm 100% you have the correct zone configured. Many times there are zones with similar names that have different times.

So, without adding information what you see in HA, with screenshots of the entities, the zone you have configured (screenshot) as well as the zone you have in ESP app (screenshot), don't expect any help here. Its close to, if not, impossible to assist without the info.

**Comment by zs3y** [comment]
Sorry, ok, don't use the app. myself, but my betterer half has Eskomsepush on her cell phone and yes the times have been the same as on Eksdom/Eishkoms website, add two hours and then it would fit the local times... so their times correspond to loadshed/rolling blackout times provided by Eskom and the time would be correct if we used UTC and not SAST...

**Comment by tinuva** [comment]
For just a moment, imagine it is not a UTC or 2 hour diff problem.

Show us a screenshot with the area name and times from your other half
You already have a screenshot of the area name in HA above at least.

**Comment by zs3y** [comment]
![image](https://user-images.githubusercontent.com/126156486/235634929-e7bca62f-dc62-43c8-9d04-7e1f0236db5d.png)



ok, that's a screenahot off the Apple cell, 12:00 to 14:30, which is also what Eskom's end is stating... also my aquaintance who's between Willowmore and Uniondale also has his times reported by Eskom at least, not sure if he uses the ESP app., also two hours before the actual event (thus must surmise in UTC) and this was never the case until shortly after De Ruiter left, whereafter their times for power outages were always 2 hours before the event... and same with ESP app, at least for us here...

**Comment by zs3y** [comment]
I see you've been dumbstruck, since I imagined, for about 24 hours that it is not a UTC or 2 hour problem, it hasn't come right, it *IS* a 2 hour problem and the only thing that would make sense to me is that the times provided by both Eskom and ESP are in UTC, since early March already... any other bright ideas other than attempting to imagining a different reason for the 2 hour discrepancy?

**Comment by zs3y** [comment]
Yet another screenshot... note the *actual* blackout started at 14:01:09 local time and according to the ESP integration towards the bottom left is indicating that the blackout started at 12:00, which is the indicated time from Eskom and ESP, but wrong and their times are 2 hours before the actual event... only conclusion I can come to is UTC... also note the prior blacout from 06:00:38 to 08:00:41 which according to ESP etc. should have ended by 06:30 latest... UTC, yes, SAST no....

![Screenshot 2023-05-03 at 14 18 49](https://user-images.githubusercontent.com/126156486/235914045-05b59e1c-8e80-44f8-bd95-d9d7cb6a0ba5.png)

**Comment by tinuva** [comment]
> I see you've been dumbstruck, since I imagined, for about 24 hours that it is not a UTC or 2 hour problem, it hasn't come right, it _IS_ a 2 hour problem and the only thing that would make sense to me is that the times provided by both Eskom and ESP are in UTC, since early March already... any other bright ideas other than attempting to imagining a different reason for the 2 hour discrepancy?

Good on the attitude.

If there really is a timezone issue (aka UTC vs SAST), it is with YOUR Home Assistant install and not the integration nor ESP.

According to the ESP app on my phone, Gariep (16)'s slot started 14:00.

**Comment by zs3y** [comment]
Ok, how? you saw the screenshot of the ESP app. it was 2 hours ahead of the actual time the power went south... and so if the Eskom loadshed schedule and so is the API query via HomeAssistant next you'l tell me I'm in a different timezone and that is why... how can I get from 2 different devices the time 2 hours off what you are seeing and they correspond with Eskom's pubished schedule? Please check out what Eskom's side is giving you and let me know whether that also is different from what I'm seeing...

Also if MY home assistant install is the problem, where would you think it may hide the problem? There isn't much one can screw up, unless there's some setting I'm not aware, which I guess is not impossible...

![Screenshot 2023-05-03 at 16 18 46](https://user-images.githubusercontent.com/126156486/235944672-a617194d-6980-41f8-bf2f-7536422a0ea4.png)

**Comment by zs3y** [comment]
Ho hum, i guess you're employed by Eishkom or have ties to them, all of a sudden their schedule has changed to the right time... it seems and also the ESP schedule followed suit, somewhat, let me check the cell and my laptop... ok, nice attitude my butt dude, either you work for ESP or Eskom and got this sorted or, someone from one or both of those outfits saw this thread and sorted out their issues, since out of the blue, on my laptop and my desktop, Eishkom's loadshed site show more correct time for us... the jury's still out on ESP, but since they presumably screenscrape or whatever the data from Eishkom, they probably will also be correct now... except on the cell the area needed reselecting and is now 16, not 15, so presumably Home Assistant will croak and need re-configuring of the load shedding device as well, we'll see...
Now imagine that this was wrong for just about 2 months and some berk tells you its not 2 hours or a UTC thing... I'm no John Lennon and I think, neither are you....

Thanks though, if you got the relevant outfits to fix their screwup...

**Comment by wernerhp** [comment]
Thanks @tinuva for posting the correct answer in your first reply.

> If your times are off by 2 hours, first step is to confirm 100% you have the correct zone configured. Many times there are zones with similar names that have different times.

@zs3y please leave your frustrations with Eskom at home.  The community volunteering their time doesn't need sarcasm or a bad attitude.

**Comment by wernerhp** [comment]
PEBKAC
