### ISSUE TITLE
Linked website

### ISSUE THREAD

**Issue by Welsyntoffie** [wernerhp/ha.integration.load_shedding#64]
https://loadshedding.eskom.co.za/ = REJECTED so no way to find other schedule

**Comment by wernerhp** [comment]
Could you elaborate?
Where are you located?
Are you on a VPN?
What version of the integration are you using?
Please post some logs.

**Comment by Welsyntoffie** [comment]
I see now. Was trying from the work PC behind proxy that's probably blocking that website.

**Comment by wernerhp** [comment]
The latest version 1.2.0 of the integration uses the EskomSePush API and should not be calling loadshedding.eskom.co.za directly.
