### ISSUE TITLE
Editing Area Sensors

### ISSUE THREAD

**Issue by Clayton1212** [wernerhp/ha.integration.load_shedding#67]
Hi
Thank you so much for this integration. I have been successfully using it for a few months now and love it. 

One small complication I have run into since Ethekwini have released new schedules, ESP created a new area for the new schedules and the old ones are no longer in use. 
How do I edit the sensors to update it to the new area? I have looked all over to find this but just can’t seem to work it out. 

Thank you for your help

**Comment by Interquip** [comment]
Have a similar issue - in COJ they moved us from block 16 to block 8.

**Comment by DravenSA** [comment]
What i did when they move our block was remove the integration and then installed it again.
I had to then go and edit my front end, but it should only be in one or two laces if you used something lie
```
{% set area_sensor = "sensor.load_shedding_area_jhbcitypower2_16_yourarea" %}
```
And then you should be  back on track

**Comment by wernerhp** [comment]
Yes, the easiest is to remove and reconfigure the integration.  Changing areas is not something that happens that often so it was not built into the integration. Will likely add this functionality when multiple areas are supported.

**Comment by StefMicro** [comment]
installed the integration, all working great except there is a Cape Town stage sensor with Cape town schedules it seems, when it should be Tshwane. The rest of the sensors reflect my area. Updating it did not help.

**Comment by wernerhp** [comment]
> installed the integration, all working great except there is a Cape Town stage sensor with Cape town schedules it seems, when it should be Tshwane. The rest of the sensors reflect my area. Updating it did not help.

There are always two stage sensors, one for Eskom and one for Cape Town, because CoCT has different stages from the rest of the country.  These reflect the planned stages.  If you are not in CoCT you can just ignore it.

There will also be an area sensor for your area with the forecast. Forecast is where your area schedule intercepts with the stage sensor's planned schedule.

**Comment by StefMicro** [comment]
> > installed the integration, all working great except there is a Cape Town stage sensor with Cape town schedules it seems, when it should be Tshwane. The rest of the sensors reflect my area. Updating it did not help.
> 
> There are always two stage sensors, one for Eskom and one for Cape Town, because CoCT has different stages from the rest of the country. These reflect the planned stages. If you are not in CoCT you can just ignore it.
> 
> There will also be an area sensor for your area with the forecast. Forecast is where your area schedule intercepts with the stage sensor's planned schedule.

OK it's by design. Thanks Werner. Awesome integration BTW

**Comment by wernerhp** [comment]
Please help with testing the new beta
https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.4.0
