### ISSUE TITLE
Error when setting up

### ISSUE THREAD

**Issue by Sc00bs110** [wernerhp/ha.integration.load_shedding#68]
![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/63442834/a8152549-f473-4d49-a224-1d0d03501a6d)

Hi Werner, 

I am getting an error when I try to add the location in the setup. 

Is there a problem at the moment with the API or is it something I am doing when I search for the suburb?

**Comment by Sc00bs110** [comment]
My existing Home Assistant has also stopped working (not the one I am trying to set up) and is no longer displaying any load shedding forecast

![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/63442834/7d098e9c-8824-4b3b-be89-1b29898f5dbc)

**Comment by wernerhp** [comment]
Did you "See Logs for details."?  Please post them here.

**Comment by wernerhp** [comment]
Are you on the latest version 1.2.0 from HACS?

**Comment by Sc00bs110** [comment]
> Did you "See Logs for details."? Please post them here.

Found this in the logs 

Unable to get area schedule: Free account abuse detected - Limited access 🙀. Please pay if you can.
16:22:48 – (ERROR) Load Shedding (custom integration) - message first occurred at 3 June 2023 at 15:07:12 and shows up 1479 times

any idea what could be causing this?

**Comment by wernerhp** [comment]
Read the Eskom Se Push API [license agreement]( https://esp.info/license-agreement).
Probably used more than one API key from the same IP.  Reach out to ESP
https://eskomsepush.gumroad.com/l/api

**Comment by wernerhp** [comment]
It koght clear after a day or two if the abuse is no longer detected.

**Comment by Sc00bs110** [comment]
> Read the Eskom Se Push API [license agreement](https://esp.info/license-agreement). Probably used more than one API key from the same IP. Reach out to ESP https://eskomsepush.gumroad.com/l/api

Ahhh, I think that two API keys from the same IP may be the case. I have been trying to do a video on setting your integration up on a second Home Assistant box, obviously uses the same IP address. Will send them an email. 

Thanks for the great integration :-)

**Comment by Sc00bs110** [comment]
Will do that, going to delete the other key I created then

**Comment by tinuva** [comment]
Werner. It is worth pointing out some of these pitfalls on the Readme where
you instruct people on where and how to get a key.

**Comment by wernerhp** [comment]
Yeah, you can let me know or even better update the readme and create a
Pull Request.

The instructions to get an API key are pretty straightforward from the
integration's config flow (but I am biased) 😅

**Comment by threefoxco** [comment]
Hi Werner,

I have the same issue. I am getting this error: Unable to reach Provider. See Logs for details.

I checked the logs and the only error I am getting is:

2023-08-08 02:20:19.338 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

I am running v1.32.1 of HACS

Any suggestions?

thanks
Jacques

**Comment by wernerhp** [comment]
There should be more in the logs. Clear logs and try again. Please double check logs and be sure to not use more than one API key from the same IP. Screenshots of your error may also be helpful.
What version of HA and the integration are your running?
