### ISSUE TITLE
ESP status bar view

### ISSUE THREAD

**Issue by jpmeijers** [wernerhp/ha.integration.load_shedding#72]
The ESP details page looks like this
<img src="https://github.com/wernerhp/ha.integration.load_shedding/assets/948278/a8295bf1-67d7-43ed-8fc5-5ac7f3d5b672" width="400">

I would like to make this a bit more compact and only show the status bars as a card on a lovelace dashboard, something like this:
<img src="https://github.com/wernerhp/ha.integration.load_shedding/assets/948278/627cb1e3-66ea-4891-95f1-f9ffb1ad9b51" width="400">

Does anyone know how to do this?

**Comment by ribeirompl** [comment]
I got a bit [nerd-sniped](https://xkcd.com/356) yesterday evening, thus I tried implementing the ESP design using HTML/CSS/Jinja template with the custom [Lovelace HTML Jinja2 Template card](https://github.com/PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card).

<strong>Preview</strong><br/>

<table>
<tr>
<td>Dark Mode</td>
<td>Light Mode</td>
</tr>
<tr>
<td>
<img src="https://github.com/wernerhp/ha.integration.load_shedding/assets/41395992/e998f474-2da2-4fc3-9fa7-2f5c138bf2b5">
</td>
<td><img src="https://github.com/wernerhp/ha.integration.load_shedding/assets/41395992/fce26e2a-4ff4-4de9-8a2f-5c7b07bf9e1f"></td>
</tr>
</table

With day borders:

<table>
<tr>
<td>Dark Mode</td>
<td>Light Mode</td>
</tr>
<tr>
<td>
<img src="https://github.com/wernerhp/ha.integration.load_shedding/assets/41395992/9d704231-e3db-443b-9098-e88d04e46b81">
</td>
<td><img src="https://github.com/wernerhp/ha.integration.load_shedding/assets/41395992/6a43343a-486c-4ef0-965d-56bfe9ad465a"></td>
</tr>
</table

<strong>Limitations</strong><br/>

The card determines the dark/light mode based on your device's dark mode settings (not your Home Assistant profile settings), thus the card might pick the wrong dark/light mode if your Home Assistant profile is set to a different dark/light mode than your device.

The ESP API, along with this integration, only provides load-shedding schedules for future events, therefore this card won't show events that happened earlier in the day. I decided then to fade out old time slots to not deceive the user that there weren't any outages earlier in the day.

<table>
<tr>
<td>ESP Design</td>
<td>This Design</td>
</tr>
<tr>
<td>
<img src="https://github.com/wernerhp/ha.integration.load_shedding/assets/41395992/b59b9269-4732-47d0-9212-b774430768a1">
</td>
<td><img src="https://github.com/wernerhp/ha.integration.load_shedding/assets/41395992/96b3185a-7072-4385-869c-a6707309111f"></td>
</tr>
</table

<strong>Installation</strong><br/>

1. Install the [Lovelace HTML Jinja2 Template card](https://github.com/PiotrMachowski/Home-Assistant-Lovelace-HTML-Jinja2-Template-card), searchable within HACS -> Frontend.
2. Create a new "Manual" (YAML) card on your dashboard.
3. Copy the template code below into the card.
4. Edit the 3 variables at the top of the content section:
    - area_sensor (sensor): this should be the sensor for your load-shedding area.
    - number_of_days (1-7): set how many days of the forecast you'd like to see.
    - show_day_borders (true/false): aesthetic option, if you'd like borders around each day.

<details>
<summary>Click to expand the template code</summary>

```yaml
type: custom:html-template-card
ignore_line_breaks: true
content: >
    {% set area_sensor = "sensor.load_shedding_area_YOUR_AREA_ZONE_HERE" %}
    {% set number_of_days = 7 %}
    {% set show_day_borders = false %}
    <style>
        @media (prefers-color-scheme: light) {
            {% if show_day_borders %}
            .day_container {
                background-color: #fbeff3 !important;
            }
            {% endif %}

            .current_time_indicator_text,
            .current_slot_indicator_text {
                color: #785551 !important;
            }

            .current_time_indicator,
            .current_slot_indicator {
                background-color: #785551 !important;
            }

            .slot {
                background-color: #f5ddd9 !important;
            }
        }

        .day_container {
            {% if show_day_borders %}
            background-color: #2b2120;
            border-radius: 0.75rem;
            {% endif %}
            padding-top: 0.5rem;
            padding-bottom: 1.75rem;
            margin: 0.25rem 0;
        }

        h3.day_heading,
        .current_time_indicator_text,
        .current_slot_indicator_text {
            font-family: Roboto, Ubuntu, sans-serif;
            font-weight: 600;
        }

        h3.day_heading {
            font-size: 1.375rem;
            margin: 0 0 0 1rem;
        }

        .slot_container {
            display: grid;
            grid-template-columns: repeat(48, 1fr);
            gap: 0.0625rem;
            width: calc(100% - 2rem);
            margin: 0 1rem;
            line-height: 0.9375rem;
            position: relative;
        }

        .slot_container .slot:first-of-type {
            border-top-left-radius: 50%;
            border-bottom-left-radius: 50%;
        }

        .slot_container .slot:last-of-type {
            border-top-right-radius: 50%;
            border-bottom-right-radius: 50%;
        }

        .slot {
            border-radius: 15%;
            background-color: #534341;
        }

        .active_slot_stage_1 {
            background-color: #f6a829 !important;
        }

        .active_slot_stage_2 {
            background-color: #f8980d !important;
        }

        .active_slot_stage_3 {
            background-color: #e66e0e !important;
        }

        .active_slot_stage_4 {
            background-color: #e3493f !important;
        }

        .active_slot_stage_5 {
            background-color: #d93e3d !important;
        }

        .active_slot_stage_6 {
            background-color: #cf3131 !important;
        }

        .active_slot_stage_7 {
            background-color: #b21e1d !important;
        }

        .active_slot_stage_8 {
            background-color: black !important;
        }

        div.active_slot {
            background-color: black;
        }

        div.fade_slot {
            opacity:0.2;
        }

        .current_time_indicator {
            width: 0.25rem;
            position: absolute;
            height: 120%;
            top: -10%;
            border-radius: 15%;
            transform: translate(-50%, 0);
            background-color: #e6bdb7;
        }

        .current_time_indicator_text {
            position: absolute;
            bottom: 140%;
            transform: translate(-50%, 0);
            color: #e6bdb7;
        }

        .current_slot_indicator {
            width: 0.125rem;
            position: absolute;
            height: 40%;
            top: 100%;
            border-radius: 15%;
            transform: translate(-50%, 0);
            background-color: #e6bdb7;
        }

        .current_slot_indicator_text {
            position: absolute;
            top: 150%;
            transform: translate(-50%, 0);
            color: #e6bdb7;
        }
    </style>
    {% set area_schedule = state_attr(area_sensor, "forecast") %}
    <h2>Loadshedding: {{ state_attr(area_sensor, "friendly_name") }}</h2>
    {% for day_offset_idx in range(number_of_days) %}
        {% set today_datetime_midnight = now().replace(hour=0,minute=0,second=0,microsecond=0) + timedelta(days=day_offset_idx) %}
        <div class="day_container">
            <h3 class="day_heading"
                style="{% if day_offset_idx == 0 %} margin-bottom: 1.5rem;
                    {% else %} margin-bottom: 0.5rem;
                    {% endif %}">{{ today_datetime_midnight.strftime("%A, %B %-d") }}</h3>
            <div class="slot_container">
                {% set ns = namespace(active_class_name="", last_slot_was_active=false, current_slot_was_activated=false) %}
                {% for half_hour_time_slot_idx in range(48) %}
                    {% set half_hour_time_slot = today_datetime_midnight + timedelta(minutes=30*half_hour_time_slot_idx) %}
                    {% set ns.active_class_name = "" %}
                    {% set ns.current_slot_was_activated = false %}
                    {% for loadshedding in area_schedule %}
                        {% if not ns.current_slot_was_activated %}
                            {% if loadshedding["start_time"] <= half_hour_time_slot < loadshedding["end_time"] %}
                                {% if not ns.last_slot_was_active %}
                                    {% set percentage_of_region = (half_hour_time_slot_idx/48)*100 %}
                                    <span class="current_slot_indicator"
                                        style="left:{{ percentage_of_region }}%">&nbsp;</span>
                                    <span class="current_slot_indicator_text"
                                        style="left:{{ percentage_of_region }}%;
                                                {% if half_hour_time_slot.hour == 0 %}transform: none;{% endif %}">{{ half_hour_time_slot.strftime("%H:%M") }}</span>
                                {% endif %}
                                {% set ns.current_slot_was_activated = true %}
                                {% set ns.last_slot_was_active = true %}
                                {% set ns.active_class_name = "active_slot active_slot_" + loadshedding['stage']|lower|replace(' ','_') %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    {% if not ns.current_slot_was_activated %}
                        {% set ns.last_slot_was_active = false %}
                    {% endif %}
                    <div class="slot {% if now() > half_hour_time_slot + timedelta(minutes=30) %}fade_slot{% endif %} {{ ns.active_class_name }}">&nbsp;</div>
                {% endfor %}
                {% if day_offset_idx == 0 %}
                    {% set current_time_indicator_progress = now().hour*2 + now().minute/30 %}
                    {% set percentage_of_region = (current_time_indicator_progress/48)*100 %}
                    <span class="current_time_indicator"
                        style="left:{{ percentage_of_region }}%">&nbsp;</span>
                    <span class="current_time_indicator_text"
                        style="left:{{ percentage_of_region }}%">Now</span>
                {% endif %}
            </div>
        </div>
    {% endfor %}
```
</details>

**Comment by jpmeijers** [comment]
O wow this is really amazing! Thanks a lot @ribeirompl. Shout when you're in town and I'll buy you a beer/coffee.

![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/948278/dc1c0383-ffca-4619-b73b-f44089040136)

**Comment by wernerhp** [comment]
Brilliant! Great job @ribeirompl! Thank you for sharing!

**Comment by wernerhp** [comment]
https://github.com/wernerhp/ha.integration.load_shedding/blob/master/examples/card5.yaml

**Comment by Viva57** [comment]
@ribeirompl Thanks for this card. It's such a nice addition to my dashboard!

I recently started getting an error with this card though. From my logs: Error while processing template. Apart from updating my home assistant to the latest version, nothing changed on my side. 

Do you perhaps experience the same issue? 

-----------------------------------------------------------

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2231, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 177, in top-level template code
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: 'NoneType' object is not iterable

**Comment by ribeirompl** [comment]
@Viva57 I believe that issue may have been fixed with an update on 28 September.
Check that you have the latest code: https://github.com/wernerhp/ha.integration.load_shedding/blob/master/examples/card5.yaml

This was the fix for the issue: https://github.com/wernerhp/ha.integration.load_shedding/pull/81/files

Let me know if you come right 👍

**Comment by Viva57** [comment]
Ah, thanks @ribeirompl! I uodated my code and tested it for a couple of days. All seems to be good again 🙌🏼

**Comment by surekqomi** [comment]
Not sure why but I simply cannot find that card in HACS in order to make use of this impressive example. Suggestions? I'm going to try to duplicate this using the Markdown Card to see if I can make that one work for a 2nd option.

**Comment by tinuva** [comment]
> Not sure why but I simply cannot find that card in [HACS](https://hacs.xyz/) in order to make use of this impressive example. Suggestions? I'm going to try to duplicate this using the Markdown Card to see if I can make that one work for a 2nd option.
> 
> Edit: The example code works flawlessly using the [TailwindCSS Template Card](https://github.com/usernein/tailwindcss-template-card) from HACS as well

Try searching for: `HTML Jinja2 Template card`
or in your HA url, go to: /hacs/repository/205261230

**Comment by FFJacot** [comment]
Real newbie here....
I've managed to install the Jinja2 Template card, step 1 of the installation process, but then get stuck on the very next step:
"Create a new "Manual" (YAML) card on your dashboard."

I've faffled around quite a bit and can't work out where/how to do this? What am I missing?

Thanks for any guidance!

**Comment by wernerhp** [comment]
@FFJacot 
![Screenshot_20231208-071119](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/4b3a7392-9dc3-4988-936e-1f944ce15186)
![Screenshot_20231208-071140](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/37adc491-4326-4f21-917f-fc823732e05f)
![Screenshot_20231208-071157](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/89687207-b354-4d95-9d87-e882afdc39bf)

**Comment by FFJacot** [comment]
A further newbie question: I managed to work out how to give the card a title:

"title: Grahamstown 2 Load shedding"

But the title folds over in the displayed card. Is there a way of reducing the text size for the title?

**Comment by wernerhp** [comment]
Going to need a bit more info.  Please share your code and/or 1000 word picture 😉 

![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/44cbef9d-d2d9-47ab-b558-b5d5988f4695)

**Comment by FFJacot** [comment]
Here we go:
![Screenshot (8)](https://github.com/wernerhp/ha.integration.load_shedding/assets/136760952/096df3f6-3528-489e-ae5e-e70e764a699a)

**Comment by ajscheid** [comment]
https://github.com/wernerhp/ha.integration.load_shedding/blob/master/examples/card5.yaml
errors out to 404.
Can someone provide me with the yaml file?
Thanks!

**Comment by wernerhp** [comment]
https://github.com/wernerhp/ha.integration.load_shedding?tab=readme-ov-file#cards

**Comment by ajscheid** [comment]
Thanks,

Easy as py; sorry for not reading properly
