### ISSUE TITLE
Polling interval

### ISSUE THREAD

**Issue by Sboshoff76** [wernerhp/ha.integration.load_shedding#73]
Seeing as the API allows 50 calls per day, is it possible to decrease the polling interval to 20/30 mins to catch unscheduled changes quicker?

**Comment by wernerhp** [comment]
You can hack this locally if you want by adjusting these constants.
![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/023b7a2c-7d61-4b88-8ee2-1e5e55a694af)


![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/6c96b230-0c56-46d7-ae7a-357a994b92b8)
