### ISSUE TITLE
Atomic calendar card start time wrong when stage changes during slot

### ISSUE THREAD

**Issue by jpmeijers** [wernerhp/ha.integration.load_shedding#74]
Before 16h we were on stage 1. After 16h we are on stage 3. We have a load shedding slot from 14h-16h30.

Before 16h the card showed the slot correctly/completely.
After 16h the card shows the slot to be from 16h to 16h30.

![Screenshot_20230818_160240](https://github.com/wernerhp/ha.integration.load_shedding/assets/948278/a455da04-f697-418c-89f0-ec4548675f4a)
![20230818_160206](https://github.com/wernerhp/ha.integration.load_shedding/assets/948278/352f2b0c-c67c-4408-ba75-f4fa965d9b3a)

**Comment by wernerhp** [comment]
![Screenshot_20230828-225010](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/404d77c8-5654-49fc-b439-b08dec0da605)

**Comment by jpmeijers** [comment]
Multi-stage was already selected. I'll change to 31 minutes.

![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/948278/6e615654-bb89-4568-8a3a-bc57c9b1e109)

**Comment by jpmeijers** [comment]
ESP reports:
* Stage 1 from 05:00 until 16:00
* Stage 3 from 16:00 to 05:00
* Load shedding in all stage from 14:00 until 16:30

The visualisation therefore should show the load shedding from 14:00 until 16:30, and not hide the half-hour of 16:00 until 16:30, as there is in fact load shedding happening.

**Comment by jpmeijers** [comment]
Yes I get what you are saying, but hiding the 30 mins window is not what I want to do.

> Load Shedding is Stage 1 from 05:00 until 16:00, i.e. no load shedding is forecast for the area from 14:00-16:00, because there's nothing scheduled for Stage 1 in the area

There is in fact, check my first posted image.

I opened this issue because I want to see both the 2 hours before the stage change, as well as the 30 minutes after the stage change, because there was in fact load shedding from 14h until after 16h. You can see from the Sunsynk Inverter graph in my second posted image that the grid voltage was ±3V from 14h until this photo was taken at 16:10.

So rephrased, this issue is a feature request to show the full load shedding bar in Atomic Calendar, even if the slot falls over two different stages. "Merging" the whole slot that is built up of different stages.

**Comment by wernerhp** [comment]
![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/dbe78bd2-b02c-425d-8a87-16ac1afcd915)
![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/bab9fa60-f04c-412d-8c14-1321dd6ea0f9)

Stage 1 from 05:00 - 16:00 overlaps with the Area Schedule Stage 1 (14:00-16:30), so it forecasts 14:00-16:00
Stage 3 from 16:00 - 05:00 it overlaps with the Area Schedule Stage 3 (14:00-16:30), so it forecasts 16:00-16:30

With **Multi-stage events** enabled It should have reflected as `Stage 1/Stage 3 14:00-16:30` (at least before 16:00). 
Maybe after 16:00 it changed to only `Stage 3 16:00-16:30`.  

Can you recall if it what it showed before 16:00?

**Comment by jpmeijers** [comment]
> Can you recall if it what it showed before 16:00?

Unfortunately not. I've had this issue happening twice so far, and only see it happening after the hour. I'll try and keep a better eye on the stage changes to see when we can expect a change to coincide with a slot.

Version: Looks like 1.3.0, but it's always the latest HACS is offering to update to.
