### ISSUE TITLE
Schedule Stop working

### ISSUE THREAD

**Issue by barnwern** [wernerhp/ha.integration.load_shedding#76]
My Schedule has stopped updating for a certain area in Cape Town - Area 6 Durbanville.

I use the Free API and is only 19 for the day but it does not update but did work in the beginning - could the area or name of area have changed and where can I test or get the area name exactly.

**Comment by wernerhp** [comment]
It can happen when Eskom changes areas. You can remove the addon and add it again to go through the setup and search your area again.  Can double check in the ESP app to see that the schedule is correct.  What area?

**Comment by wernerhp** [comment]
Also please post any logs

**Comment by barnwern** [comment]
Hi WernerDurbanville. Area 6I am sitting in Jhb on trip so can redo next week if it does not fix itselfThxWerner BarnardSent from my IpadOn 28 Aug 2023, at 22:40, Werner Pieterson ***@***.***> wrote:﻿
It can happen when Eskom changes areas. You can remove the addon and add it again to go through the setup and search your area again.  Can double check in the ESP app to see that the schedule is correct.  What area?

**Comment by tinuva** [comment]
> Hi Werner Durbanville. Area 6 I am sitting in Jhb on trip so can redo next week if it does not fix itself Thx Werner Barnard

I am also in Durbanville area 6 and it works fine. I think your issue, is related to the schedule not updating on long running instance.

The work around is an automation which reloads the integration.

**Comment by wernerhp** [comment]
@barnwern any luck?

**Comment by githubfreddieve** [comment]
Lots of effort to reinstall (finding the area again eats up tokens), but the integration doesn't set up the sensor.load_shedding_stage_eskom sensor anymore, so none of the code works

**Comment by wernerhp** [comment]
@githubfreddieve  it would help a lot if you provided more information.

Please post your Settings > System > Logs.  Filter by searching for `load_shedding`.
What version of HA are you running?
Is it a new problem?

How frequently do you reinstall this integration?   

The free ESP API tier allows for 50 credits per day.  This integration uses 25 per day once it's set up.  Searching for your area uses 5, but this is only required to setup assuming you don't waste API calls by searching around for your area.

**Comment by wernerhp** [comment]
Did you use more than one ESP API Key?  Because that will get both keys banned for 24 hours...

**Comment by githubfreddieve** [comment]
Yes, multiple... how do I get my sensor.load_shedding_stage_eskom back though? Even if I wait for that unbanning

**Comment by wernerhp** [comment]
Wait 24hrs for the key to be unbanned...then reload the integration
![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/c4b17db6-534e-4c11-ae35-abc5a9ba9ebb)

or remove and set it up from scratch in 24 hours.   If you have issues with the key (which it sounds like you might have since you paid and it sounds like it's banned) then try reaching out to @Dan or @Herman on the #eskomsepush channel on #zatech 
https://zatech.co.za/ .  They'll be able to sort out your key.

**Comment by githubfreddieve** [comment]
> Wait 24hrs for the key to be unbanned...then reload the integration ![image](https://user-images.githubusercontent.com/2578772/273458084-c4b17db6-534e-4c11-ae35-abc5a9ba9ebb.png)
> 
> or remove and set it up from scratch in 24 hours. If you have issues with the key (which it sounds like you might have since you paid and it sounds like it's banned) then try reaching out to @dan or @herman on the #eskomsepush channel on #zatech https://zatech.co.za/ . They'll be able to sort out your key.

This worked well. From scratch.
Thanks for referral to zatech - useful for future!
