### ISSUE TITLE
Doesent work anymore

### ISSUE THREAD

**Issue by ChristoffBo** [wernerhp/ha.integration.load_shedding#77]
It accepts my API but wont accept any area.

Does the same on another instance i also manage

unable to reach provider. see logs, but i cannot find anything in the logs

**Comment by wernerhp** [comment]
Is the other instance on the same IP? If so, read the Eskom Se Push API Terms. API keys likely suspended due to breach of terms.

Check the logs again.  Search for load_shedding

**Comment by ChristoffBo** [comment]
Hi, No Different IP Addresses, different API Keys. already created different API Key for mine, same result. checked again searched the logs for load_shedding, no logs found. deleted off the intergation and reinstalled VIA hacs and manually. same result aswell

**Comment by ChristoffBo** [comment]
Intresting, just pushed my HA through a vpn and now it connects seems to be an issue with my service provider.

Thank you anyways.

kind regards

**Comment by wernerhp** [comment]
Interesting...keep me posted if tou learn more.  Which ISP?

**Comment by tinuva** [comment]
Probably afrihost or the likes that does CGNAT. Meaning too many people on same shared nat ip.

**Comment by ChristoffBo** [comment]
Hi, correct NAT its a local ISP. Will run mine on a VPN.

Thank you

**Comment by creed6312** [comment]
Hi, I am getting a similar problem and this is what I see in the logs, any ideas?

2025-02-25 20:47:28.005 ERROR (MainThread) [custom_components.load_shedding.config_flow] Unable to initialise SePush API: Unable to get areas from SePush.

**Comment by wernerhp** [comment]
Send an email to sales@esp.info with your API Key
