### ISSUE TITLE
Schedule funnies

### ISSUE THREAD

**Issue by rengro46** [wernerhp/ha.integration.load_shedding#78]
Hi Werner, 

Awesome integration, thanks again!
Interesting one, looking at my ESP app on my phone it shows my next slot to be at 10pm tonight, looking at the integration schedule i get these weird 30min slots after level changes at 4pm, why would that be? 

See screenshot for 30min slot at 4pm today, tomorrow and Thursday. 

![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/54939776/e9d3dd35-d382-45af-8175-2fed900e537a)

Mmm, looking at ESP API Area information query with Postman, I can see it would have had a slot form 2:00pm - 4:30pm if stage 4 had been in effect at 2:00pm, yet it was not, so this 30 min slot should be stripped out, since Eskom does not apply it that way? 

![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/54939776/7ea39a9b-4347-4771-a688-672f6774f582)

**Comment by wernerhp** [comment]
Stage 4 only starts at 16:00, so your 14:00-16:30 slot is only really from 16:00-16:00.  You will generally not have load shedding then.

Change to 31m and it should remove that entry.
![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/2578772/27800146-9e3b-4b64-b0af-cc7bf4f3d86e)

**Comment by jpmeijers** [comment]
Not really the same issue. In the case of #74 there was load shedding schedule before and after the stage change, so this plugin incorrectly hid the 14h-16h part.

**Comment by wernerhp** [comment]
> Not really the same issue. In the case of #74 there was load shedding schedule before and after the stage change, so this plugin incorrectly hid the 14h-16h part.

Works as intended. https://github.com/wernerhp/ha.integration.load_shedding/issues/74#issuecomment-1697645475
