### ISSUE TITLE
Can't search area

### ISSUE THREAD

**Issue by Shaunpottie** [wernerhp/ha.integration.load_shedding#79]
I just get this error when trying to search area - Unable to reach Provider. See Logs for details.

I have even tried to search other areas to see if it works like Milnerton, still nothing same error.

I don't know how to find the logs to see the problem?

I must just add, I deleted my old install of it so I could make changes, I got a new API key and tried installing everything again, and this is when I get this error.

**Comment by wernerhp** [comment]
Your problem is getting a new API key.  See the ESP API Terms & Conditions.
Try waiting 24 hours before using only one key.

**Comment by Shaunpottie** [comment]
Thank you, really appreciate your help.

I restored my backup again and it eventually came right again a couple of hours after the restore, I don't know if the API side was just down from Eskomsepush.

Werner one thing I really wanted to ask is how do you change the area you in or zone you fall under?

Is the only way to delete it and reinstall it again so you initiate the search for you area again?

Thank you for all your work, this add on is awesome.

**Comment by wernerhp** [comment]
Yes, currently the only way is to delete and re-add it.  
It's not something that's done very often, so I didn't spend time implementing a way to edit the area.

**Comment by Shaunpottie** [comment]
No problem, it's would probably never be used.

Thank you, just wanted to check if there was another way.

Have an awesome day.
