### ISSUE TITLE
New City of Johannesburg loadshedding slots

### ISSUE THREAD

**Issue by ZAAJR** [wernerhp/ha.integration.load_shedding#85]
CoJ has released new loadshedding slots as of a couple of days ago. I don't seem to be able to pull through the new details into Home Assistant. Anyone else having the same issue?

**Comment by rameezk** [comment]
I had to remove and re-add the integration. Once I did, the new areas pulled through. It will be prefixed with `jhbcitypower3` or have the “new” emoji next to the name.

**Comment by ZAAJR** [comment]
I tried that, but still no luck. Will try again, though.

**Comment by ZAAJR** [comment]
It took a couple of attempts, but rameezk's suggestion did eventually resolve it.

- Remove Loadshedding integration
- Restart HA
- Add Loadshedding integration through HACS
- Restart HA
