### ISSUE TITLE
Entities unavailable in City of Johannesburg 

### ISSUE THREAD

**Issue by meneerfrikkie** [wernerhp/ha.integration.load_shedding#86]
Hi there, all my entities have become unavailable for a City of Johannesburg region since the load shedding schedules needed to be readded on the ESP app, could one kindly assist, many thanks!

**Comment by fragtion** [comment]
I was in the same boat and eventually got it working. Try these steps

1) Make sure you've backed up your API key or at least have that on hand ready to use, then:
2) Navigate to: Settings -> Devices & services -> Load shedding
3) Under "Integration entries" on the right side, remove the instance of "Load shedding" (it should contain 1 device and 5 entities)
4) Click "Add entry" and follow the wizard to select/add your new city power area

If that doesn't work:
1) Make sure you've backed up your API key or at least have that on hand ready to use, then:
2) Navigate to: HACS -> Integrations -> Load shedding
3) Click the settings dots at top right, and click Remove.
* It may ask you to delete the configuration, in which case click Navigate and remove using the steps we just outlined in the previous section to remove the integration configuration.
4) Re-add the integration from scratch by going back to HACS -> Integrations -> EXPLORE & DOWNLOAD REPOSITORIES and then seach for "Load shedding". I used the master branch and it worked for me

**Comment by wernerhp** [comment]
https://github.com/wernerhp/ha.integration.load_shedding/issues/85
This happens when City Power changes their schedules.
Thanks for the nice instructions @fragtion

**Comment by fouriec1** [comment]
Hi, I have the same issue as @meneerfrikkie 

I also get the following error 

API None/None
TypeError: unsupported type for timedelta minutes component:
NoneType

Any advice will be appreciated.

**Comment by wernerhp** [comment]
The answer is right there... ☝️

**Comment by meneerfrikkie** [comment]
Thank you very much @fragtion , managed to come right after following your instructions :)
