### ISSUE TITLE
Unable to reach Provider. See Logs for details.

### ISSUE THREAD

**Issue by kobusdbr** [wernerhp/ha.integration.load_shedding#88]
Good Day. 

I am trying to set up Loadshedding integration in Home assistant but when I type in the area I just get "Unable to reach Provider. See Logs for details."

Please advise

Regards

**Comment by kgaugelo-seoka** [comment]
I am getting the same error on my side also. I tried to check the search area functionality on nodered and its working.

**Comment by wernerhp** [comment]
Please "See Logs for details".  search logs for load_shessing and post here
Are you using more one API key?

**Comment by kgaugelo-seoka** [comment]
My issue is now fixed. I had the same API key on the configuration.yaml code. After removing it on the Configration.yaml code and  the next API call I was able to add the integration to HA
