### ISSUE TITLE
Unable to reach Provider. See Logs for details.

### ISSUE THREAD

**Issue by Pieterk29** [wernerhp/ha.integration.load_shedding#90]
Hi, 

I am trying to install your integration, but keep getting the following error. I have installed fresh version of HA, but still the same issue: 
![image](https://github.com/wernerhp/ha.integration.load_shedding/assets/140438011/6fbf03f3-06c4-4643-9740-625c8a7893d2)

**Comment by wernerhp** [comment]
What do the logs say?

**Comment by Pieterk29** [comment]
> What do the logs say?

Hi Werner, I tried to download your integration again and it works this time around.
