### ISSUE TITLE
Status alert code producing an error but did not before.

### ISSUE THREAD

**Issue by corbrink** [wernerhp/ha.integration.load_shedding#91]
Lately I'm getting this error woth the markdown card code for the status alert:
"TypeError: unsupported type for timedelta minutes component: StrictUndefined"

How do I fix it please?

**Comment by wernerhp** [comment]
When dod you add the markdown card? Made some fixes a while back. You might want to try recreating it from the [latest example](https://github.com/wernerhp/ha.integration.load_shedding/blob/master/examples/dashboards/status_alert.yaml).

**Comment by corbrink** [comment]
I used your code and only changed the sensor to my location. It worked fine until about a week ago when it started giving the error and displayed nothing. I deleted and reinstalled the integration and it works again.

**Comment by corbrink** [comment]
This seems to be an occurance on the RPi if you don't regularly reboot the unit.

**Comment by wernerhp** [comment]
> This seems to be an occurance on the RPi if you don't regularly reboot the unit.

The `TypeError: unsupported type for timedelta minutes component: StrictUndefined` error?

**Comment by wernerhp** [comment]
Which dashboards from the examples do you use?

I see the [example](https://github.com/wernerhp/ha.integration.load_shedding/tree/master/examples) for `card1.yaml` is a little brittle.

**Comment by wernerhp** [comment]
Ok, I think I found the issue.  Please update your Status alert card to the [latest example](https://github.com/wernerhp/ha.integration.load_shedding/blob/v1.3.2/examples/dashboards/status_alert.yaml)

**Comment by corbrink** [comment]
I use all the dashboard yaml's, none of the automations.

**Comment by corbrink** [comment]
will do, thanks for letting me know. I will give update after a couple of
days.

**Comment by wernerhp** [comment]
Oh 💩 , I clearly messed that up 😂 #notamorningperson
Let me try that again...

**Comment by wernerhp** [comment]
https://github.com/wernerhp/ha.integration.load_shedding/releases/tag/v1.3.3
